// <auto-generated />
namespace Temple.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReceiptGeneration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReceiptGeneration));
        
        string IMigrationMetadata.Id
        {
            get { return "201701130400405_ReceiptGeneration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
